config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

dbt_airport_system:
  outputs:
    dev:
      type: vertica
      host: localhost
      port: 5433
      username: dbadmin
      password: ""
      database: vertica
      schema: public

  target: dev