{
 "title": "airports_dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "active airports total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(airport_code) AS active_airports\r\nFROM presentation.airports_traffic\r\nWHERE flight_date::DATE >= NOW() - INTERVAL '30 days'\r\n  AND (flights_in > 0 OR flights_out > 0);\r\n",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "active airports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT flight_date::DATE, COUNT(DISTINCT airport_code) AS active_airports\r\nFROM presentation.airports_traffic\r\nWHERE flight_date::DATE >= NOW() - INTERVAL '30 days'\r\n  AND (flights_in > 0 OR flights_out > 0)\r\nGROUP BY flight_date::DATE\r\nORDER BY flight_date::DATE;\r\n",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "passenger traffic, airports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT airport_code, \r\n       SUM(passengers_in + passengers_out) AS total_passengers\r\nFROM presentation.airports_traffic\r\nWHERE flight_date::DATE >= NOW() - INTERVAL '30 days'\r\nGROUP BY airport_code;\r\n",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "flights_traffic, airports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT airport_code, \r\n       SUM(flights_in + flights_out) AS total_flights\r\nFROM presentation.airports_traffic\r\nWHERE flight_date::DATE >= NOW() - INTERVAL '30 days'\r\nGROUP BY airport_code;\r\n",
     "schema": "select schema"
    }
   ]
  }
 ]
}