{
 "title": "passengers_dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "unique passengers, count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE(created_at) AS flight_date, \r\n       COUNT(DISTINCT passenger_id) AS unique_passengers\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days'\r\nGROUP BY flight_date\r\nORDER BY flight_date;",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "gmv total, usd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE(created_at) AS flight_date, \r\n       SUM(purchase_sum) AS total_gmv\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days'\r\nGROUP BY flight_date\r\nORDER BY flight_date;",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "unique passengers, count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT passenger_id) AS unique_passengers\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days';",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "avg flights count per passenger",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(flights_number) AS avg_flights_per_passenger\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days';",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "avg bill, usd",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(purchase_sum) AS avg_ticket_price\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days';",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "passengers gmv, usd",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT customer_group, \r\n       SUM(purchase_sum) AS group_gmv\r\nFROM presentation.frequent_flyers\r\nWHERE created_at >= NOW() - INTERVAL '30 days'\r\nGROUP BY customer_group;",
     "schema": "select schema"
    }
   ]
  }
 ]
}